export {
	ALL_TAGS_KEY,
	createTag,
	deleteTag,
	fetchAllTags,
	getTagApiErrorMessage,
	normalizeTagListResponse,
	patchTag,
	revalidateTagLists,
	TAGS_ADMIN_LIST_PATH,
	TAGS_BASE,
	TAGS_LIST_PATH,
	TAGS_PER_PAGE,
	tagAdminDetailPath,
	tagsAdminListKey,
	useAdminTag,
	useAdminTags,
	useAllTags,
} from "./useTags";
