export {
	createOpportunity,
	deleteOpportunity,
	getOpportunityApiErrorMessage,
	normalizeOpportunityListResponse,
	OPPORTUNITIES_ADMIN_LIST_PATH,
	OPPORTUNITIES_BASE,
	OPPORTUNITIES_LIST_PATH,
	OPPORTUNITIES_PER_PAGE,
	opportunitiesListKey,
	opportunityAdminDetailPath,
	opportunityDetailPath,
	patchOpportunity,
	revalidateOpportunityDetailCaches,
	revalidateOpportunityLists,
	useAdminOpportunity,
	useOpportunities,
	useOpportunity,
} from "./useOpportunities";
